  set-option        -g  mouse on
  set               -g  status-keys vi
  set               -g  default-shell /bin/bash
  set               -g  status-position top
  set               -g  status-style fg=black,bg=green
  set               -g  status-right "#(date +%%H:%%M -u)"
  set-option        -g  status-style  fg='#bbe0e6'
  set-option        -g  message-style fg='#26c06d'
  set-option        -g  mode-style "fg=#1d1f21,bg=#1AA053"
  set-option        -g  pane-border-status top
  set-option        -g  pane-border-format " [ ###P #T ] "
  set-window-option -g  allow-rename off
  set-option        -wg automatic-rename off
  set-option        -g  allow-rename off
  set-option        -g  prefix C-space
  
  unbind-key |
  unbind-key -
  
  bind y setw synchronize-panes on
  bind C-s setw synchronize-panes off
  bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -sel clip"
  bind | splitw -hc "`pwd`"
  bind r source-file $XH/tmux/tmux.conf \; display "Tmux config loaded: $XH/tmux/tmux.conf"
  bind P command-prompt -I "" { select-pane -T "%%" }
  
  unbind h
  unbind j
  unbind k
  unbind l
  unbind C-h
  unbind C-j
  unbind C-k
  unbind C-l

  bind-key | split-window -h -c "#{pane_current_path}"
  bind-key - split-window -v -c "#{pane_current_path}"

  bind-key j select-pane -D
  bind-key h select-pane -L
  bind-key k select-pane -U
  bind-key l select-pane -R
  bind-key C-h resize-pane -L
  bind-key C-j resize-pane -D
  bind-key C-k resize-pane -U
  bind-key C-l resize-pane -R
  bind-key y setw synchronize-panes on
  bind-key C-s setw synchronize-panes off
